site_name: Be-Secure
theme: windmill
nav:
  - Home: ./besec_info/be-Secure-introduction.md
  - Projects and utilities: ./besec_info/bes_utilities.md
  - Developers: ./besec_info/Developers.md
  - Documentation: ./besec_info/Documentation.md
  - Licence: ./besec_info/license.md
  - FAQ: ./besec_info/faq.md
  - WIKI: ./besec_info/wiki.md
