site_name: Be-Secure
theme: windmill
nav:
  - Home: ./besec_info/home.md
  - Getting started with Be-Secure: ./besec_info/Be-secure_gettingstr.md
  - Tech stack & Security Assessment:  ./besec_info/Tech_stack.md
  - OSS projects we track:  ./besec_info/tracked_projects.md
  - OSS projects we contribute:  ./besec_info/Project_contribute.md
  - Be-Secure Community Dashboard:  ./besec_info/Community_dashboard.md
  - More details: ./besec_info/More_info.md
  - WIKI: ./besec_info/wiki.md
